"""initial

Revision ID: 5e3a6b21f616
Revises: 
Create Date: 2025-03-02 15:24:15.152228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3a6b21f616'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('short_key', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_url_original_url'), 'short_url', ['original_url'], unique=False)
    op.create_index(op.f('ix_short_url_short_key'), 'short_url', ['short_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_url_short_key'), table_name='short_url')
    op.drop_index(op.f('ix_short_url_original_url'), table_name='short_url')
    op.drop_table('short_url')
    # ### end Alembic commands ###
